import argparse
import os
from typing import Any, Dict, Iterable, List

from utils import get_all_geojson_files

# All available fields in GeoJSON features
AVAILABLE_FIELDS = [
    "loc_id",
    "latitude",
    "longitude",
    "name",
    "tech",
    "upgrade",
    "gnaf_pid",
    "tech_change_status",
    "program_type",
    "target_eligibility_quarter",
]

# Default fields to export (maintains backward compatibility)
DEFAULT_FIELDS = ["loc_id", "latitude", "longitude"]


def iter_feature_data(show_progress: bool = True, fields: List[str] = None) -> Iterable[Dict[str, Any]]:
    """Yield feature data as a dictionary for every feature across all GeoJSON files.

    Args:
        show_progress: Whether to show progress while scanning files
        fields: List of field names to extract. If None, extracts all available fields.

    Skips features missing locID or coordinates.
    """
    if fields is None:
        fields = AVAILABLE_FIELDS

    for _filename, geojson_data in get_all_geojson_files(show_progress=show_progress, rewrite_geojson=False):
        for f in geojson_data.get("features", []):
            props = f.get("properties", {})
            loc_id = props.get("locID")
            geom = f.get("geometry") or {}
            coords = geom.get("coordinates") or [None, None]

            # Skip features without loc_id or coordinates
            if not loc_id:
                continue
            if coords is None or len(coords) < 2 or coords[0] is None or coords[1] is None:
                continue

            lng, lat = coords[0], coords[1]

            # Build field extraction mapping
            field_extractors = {
                "loc_id": loc_id,
                "latitude": float(lat),
                "longitude": float(lng),
                "name": props.get("name", ""),
                "tech": props.get("tech", ""),
                "upgrade": props.get("upgrade", ""),
                "gnaf_pid": props.get("gnaf_pid", ""),
                "tech_change_status": props.get("tech_change_status", ""),
                "program_type": props.get("program_type", ""),
                "target_eligibility_quarter": props.get("target_eligibility_quarter", ""),
            }

            # Build the result dictionary with requested fields
            result = {field: field_extractors[field] for field in fields}

            yield result


def write_sql(output_path: str, rows: Iterable[Dict[str, Any]], fields: List[str], dedupe: bool = True) -> int:
    """Write rows to SQL dump file with specified fields. Returns count written.

    Args:
        output_path: Path to write the SQL file
        rows: Iterable of dictionaries containing feature data
        fields: List of field names to include in the SQL
        dedupe: Whether to deduplicate by loc_id
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    seen = set()
    count = 0

    with open(output_path, "w", encoding="utf-8") as f:
        # Write CREATE TABLE statement (without secondary indexes for faster import)
        f.write("-- MariaDB dump for locids table\n")
        f.write("-- Generated by export_locids_sql.py\n\n")
        f.write("-- Disable checks for faster import\n")
        f.write("SET FOREIGN_KEY_CHECKS=0;\n\n")
        f.write("CREATE TABLE IF NOT EXISTS locids (\n")
        f.write("    locid VARCHAR(20) PRIMARY KEY,\n")
        f.write("    latitude DECIMAL(10, 7) NOT NULL,\n")
        f.write("    longitude DECIMAL(10, 7) NOT NULL,\n")
        f.write("    name VARCHAR(255),\n")
        f.write("    tech VARCHAR(50),\n")
        f.write("    upgrade VARCHAR(50),\n")
        f.write("    gnaf_pid VARCHAR(50),\n")
        f.write("    tech_change_status VARCHAR(100),\n")
        f.write("    program_type VARCHAR(100),\n")
        f.write("    target_eligibility_quarter VARCHAR(20)\n")
        f.write(");\n\n")

        # Write INSERT statements in batches
        batch_size = 1000
        batch = []

        for row in rows:
            if dedupe and "loc_id" in row:
                if row["loc_id"] in seen:
                    continue
                seen.add(row["loc_id"])

            batch.append(row)
            
            if len(batch) >= batch_size:
                _write_insert_batch(f, batch)
                count += len(batch)
                batch = []

        # Write remaining rows
        if batch:
            _write_insert_batch(f, batch)
            count += len(batch)

        # Create index after all data is loaded (much faster than during inserts)
        f.write("\n-- Create index after data load for better performance\n")
        f.write("CREATE INDEX IF NOT EXISTS idx_lat_lng ON locids (latitude, longitude);\n\n")
        f.write("-- Re-enable checks\n")
        f.write("SET FOREIGN_KEY_CHECKS=1;\n")

    return count


def _write_insert_batch(f, batch: List[Dict[str, Any]]) -> None:
    """Write a batch of INSERT statements to the file."""
    if not batch:
        return
    
    f.write("INSERT INTO locids (locid, latitude, longitude, name, tech, upgrade, gnaf_pid, tech_change_status, program_type, target_eligibility_quarter) VALUES\n")
    
    for i, row in enumerate(batch):
        # Escape single quotes in string values
        def escape_value(value):
            if value is None or value == "":
                return "NULL"
            if isinstance(value, (int, float)):
                return str(value)
            # Escape single quotes by doubling them
            escaped = str(value).replace("'", "''")
            return f"'{escaped}'"
        
        locid = escape_value(row.get("loc_id", ""))
        latitude = row.get("latitude", 0)
        longitude = row.get("longitude", 0)
        name = escape_value(row.get("name", ""))
        tech = escape_value(row.get("tech", ""))
        upgrade = escape_value(row.get("upgrade", ""))
        gnaf_pid = escape_value(row.get("gnaf_pid", ""))
        tech_change_status = escape_value(row.get("tech_change_status", ""))
        program_type = escape_value(row.get("program_type", ""))
        target_eligibility_quarter = escape_value(row.get("target_eligibility_quarter", ""))
        
        values = f"({locid}, {latitude}, {longitude}, {name}, {tech}, {upgrade}, {gnaf_pid}, {tech_change_status}, {program_type}, {target_eligibility_quarter})"
        
        if i < len(batch) - 1:
            f.write(f"    {values},\n")
        else:
            f.write(f"    {values};\n\n")


def main():
    parser = argparse.ArgumentParser(description="Export NBN data to a SQL dump file from GeoJSON results")
    parser.add_argument(
        "--output",
        default=os.path.join("results", "locids.sql"),
        help="Path to write the SQL file (default: results/locids.sql)",
    )
    parser.add_argument(
        "--no-dedupe",
        action="store_true",
        help="Do not deduplicate by loc_id (default is to dedupe)",
    )
    parser.add_argument(
        "--no-progress",
        action="store_true",
        help="Disable progress output while scanning files",
    )

    args = parser.parse_args()

    # Always export all fields for SQL dump
    fields = AVAILABLE_FIELDS

    rows = iter_feature_data(show_progress=not args.no_progress, fields=fields)
    written = write_sql(args.output, rows, fields, dedupe=not args.no_dedupe)
    print(f"Wrote {written} rows to {args.output}")


if __name__ == "__main__":
    main()
